# Generated by Django 5.0.4 on 2024-04-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
