# Generated by Django 5.0.4 on 2024-04-16 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("a_posts", "0008_alter_comment_options_reply"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="parent_post",
        ),
        migrations.AddField(
            model_name="reply",
            name="parent_comment",
            field=models.ForeignKey(
                default="none",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="a_posts.comment",
            ),
            preserve_default=False,
        ),
    ]
